# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
# Liquibase
spring.liquibase.change-log=classpath:db.changelog/public/db.changelog-master.yaml
# Quartz Scheduler
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.jobStore.tablePrefix=qrtz_
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
spring.data.redis.database=0
# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.type-handlers-package=dev.ngb.base_hub.common.config.mybatis.type_handler
# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath*:graphql/**/
# Scalar
scalar.enabled=true
spring.threads.virtual.enabled=true
# kafka
spring.kafka.bootstrap-servers=localhost:9095
spring.kafka.consumer.group-id=my-group
