enum AppStatus {
    ACTIVE
    INACTIVE
    ARCHIVED
}

input AppFilter {
    query: String
    code: String
    status: String
    createdFrom: String
    createdTo: String
}

type AppQueryResult {
    id: ID
    name: String
    code: String
    description: String
    status: AppStatus
    createdById: ID
    updatedById: ID
    createdAt: String
    updatedAt: String
    auditUsers: AuditUserPair
}

type PaginatedApp {
    items: [AppQueryResult]
    pagination: Pagination
}

enum AppVersionStatus {
    DRAFT
    DEVELOPMENT
    PUBLISHED
    DEPRECATED
}

input AppVersionFilter {
    query: String
    status: String
    features: [String]
    releasedFrom: String
    releasedTo: String
    createdFrom: String
    createdTo: String
}

type AppVersionQueryResult {
    id: ID
    appId: ID
    version: String
    changelog: String
    status: AppVersionStatus
    releasedAt: String
    createdById: ID
    updatedById: ID
    createdAt: String
    updatedAt: String
    auditUsers: AuditUserPair
}

type PaginatedAppVersion {
    items: [AppVersionQueryResult]
    pagination: Pagination
}