spring.config.import=classpath:/application-common.properties
server.port=8088
server.servlet.context-path=/api/system-admin
spring.application.name=base-hub-system-admin
spring.application.version=1.0.0
